language: node_js
node_js:
  - 15

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
      - ${SERVICE_PATH}/node_modules

  install:
    - npm install -g serverless
    - travis_retry npm install
    - cd ${SERVICE_PATH}
    - travis_retry npm install
    - cd -

  script:
    - cd ${SERVICE_PATH}
    - serverless deploy -s ${TRAVIS_BRANCH}
    - cd -

jobs:
  include:
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Frontend"
      env:
        - SERVICE_PATH="frontend"

notifications:
  slack: glpg-hq:OIznQNWGQIGXE4DbypgODTcP
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of **%{repository_slug}@%{branch}** by %{author}"
      - "Time: **%{duration}**"
      - "Status: Build **%{result}**"
