language: node_js
node_js:
  - 15

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
      - ${SERVICE_PATH}/node_modules

  install:
    - npm install -g serverless --component
    - travis_retry npm install
    - cd ${SERVICE_PATH}
    - travis_retry npm install
    - cd -

  script:
    - cd ${SERVICE_PATH}
    - serverless deploy -s ${TRAVIS_BRANCH}
    - cd -

jobs:
  include:
    - <<: *DEPLOY_SERVICE_JOB
      name: 'Deploy Frontend'
      env:
        - SERVICE_PATH="frontend"

notifications:
  slack:
    - rooms:
        - glpg-hq:OIznQNWGQIGXE4DbypgODTcP
      on_success: always
      on_failure: never
      if: type = push
      template:
        - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of *%{repository_name}@%{branch}* by _%{author}_ *%{result}*! :white_check_mark:'
        - 'Time: *%{duration}*'
        - 'Commit: _%{commit_subject}_'
    - rooms:
        - glpg-hq:OIznQNWGQIGXE4DbypgODTcP
      on_success: always
      on_failure: never
      if: type = pull_request
      template:
        - 'Pull Request <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of *%{repository_name}@%{branch}* by _%{author}_ *%{result}*! :white_check_mark:'
        - 'Time: *%{duration}*'
        - 'Commit: _%{commit_subject}_'
    - rooms:
        - glpg-hq:OIznQNWGQIGXE4DbypgODTcP
      on_success: never
      on_failure: always
      if: type = push
      template:
        - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of *%{repository_name}@%{branch}* by _%{author}_ *%{result}*! :rotating_light:'
        - 'Time: *%{duration}*'
        - 'Commit: _%{commit_subject}_'
    - rooms:
        - glpg-hq:OIznQNWGQIGXE4DbypgODTcP
      on_success: never
      on_failure: always
      if: type = pull_request
      template:
        - 'Pull Request <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of *%{repository_name}@%{branch}* by _%{author}_ *%{result}*! :rotating_light:'
        - 'Time: *%{duration}*'
        - 'Commit: _%{commit_subject}_'
