language: node_js
node_js:
  - 15
cache:
  directories:
    - node_modules
script:
  - cd frontend
  - npm build
notifications:
  slack: glpg-hq:OIznQNWGQIGXE4DbypgODTcP
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of **%{repository_slug}@%{branch}** by %{author}"
      - "Time: **%{duration}**"
      - "Status: Build **%{result}**"
