language: node_js
node_js:
  - '15.2.1'

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
      - ${SERVICE_PATH}/node_modules

  install:
    - npm install -g serverless
    - travis_retry npm install
    - cd ${SERVICE_PATH}
    - travis_retry npm install
    - cd -

  script:
    - cd ${SERVICE_PATH}
    - pwd
    - serverless deploy -s ${STAGE_NAME} --component
    - cd -

environments:
  - &PRODUCTION_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  - &DEVELOPMENT_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

jobs:
  include:
    - <<: *DEPLOY_SERVICE_JOB
      name: 'Deploy Frontend'
      if: branch = master
      env:
        - SERVICE_PATH="frontend"
        - STAGE_NAME=prod
        - *PRODUCTION_ENV

notifications:
  slack:
    - rooms:
        - glpg-hq:OIznQNWGQIGXE4DbypgODTcP
      on_success: always
      on_failure: never
      if: type = push
      template:
        - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of *%{repository_name}@%{branch}* by _%{author}_ *%{result}*! :white_check_mark:'
        - 'Time: *%{duration}*'
        - 'Commit: _%{commit_subject}_'
    - rooms:
        - glpg-hq:OIznQNWGQIGXE4DbypgODTcP
      on_success: always
      on_failure: never
      if: type = pull_request
      template:
        - 'Pull Request <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of *%{repository_name}@%{branch}* by _%{author}_ *%{result}*! :white_check_mark:'
        - 'Time: *%{duration}*'
        - 'Commit: _%{commit_subject}_'
    - rooms:
        - glpg-hq:OIznQNWGQIGXE4DbypgODTcP
      on_success: never
      on_failure: always
      if: type = push
      template:
        - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of *%{repository_name}@%{branch}* by _%{author}_ *%{result}*! :rotating_light:'
        - 'Time: *%{duration}*'
        - 'Commit: _%{commit_subject}_'
    - rooms:
        - glpg-hq:OIznQNWGQIGXE4DbypgODTcP
      on_success: never
      on_failure: always
      if: type = pull_request
      template:
        - 'Pull Request <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of *%{repository_name}@%{branch}* by _%{author}_ *%{result}*! :rotating_light:'
        - 'Time: *%{duration}*'
        - 'Commit: _%{commit_subject}_'
