language: node_js
node_js:
  - '15.2.1'
# Does it matter where the cache goes? I am looking at another sugestion that loads the cache under version.
# cache:
#    directories:
#     - node_modules
#     - ${SERVICE_PATH}/node_modules
#

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules ## Seems right
      - ${SERVICE_PATH}/node_modules #this would be essentially ./frontend/ node_modules there is nothing there would this brake the script

  install:
    - npm install -g serverless ## Install Serverless globally
    # - travis_retry npm install
    - cd ${SERVICE_PATH} ## Change Directory to ./frontend 
    - npm install # could this be just npm install 
    - cd -  # does is reset the directory

  script:
    - cd ${SERVICE_PATH} ## Change Directory to ./frontend 
    # - serverless deploy -s ${TRAVIS_BRANCH} --component
    - serverless --component # what is --component should it just be serverless
    - cd -

environments:
    ## Accessing Keys set in Travis.  Dev / Prod the same for now
  - &PRODUCTION_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  - &DEVELOPMENT_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

jobs:
  include:
    - <<: *DEPLOY_SERVICE_JOB
      name: 'Deploy Frontend'
      env:
        - SERVICE_PATH="frontend"
        - STAGE_NAME=prod
        - *PRODUCTION_ENV

notifications:
  slack:
    - rooms:
        - glpg-hq:OIznQNWGQIGXE4DbypgODTcP
      on_success: always
      on_failure: never
      if: type = push
      template:
        - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of *%{repository_name}@%{branch}* by _%{author}_ *%{result}*! :white_check_mark:'
        - 'Time: *%{duration}*'
        - 'Commit: _%{commit_subject}_'
    - rooms:
        - glpg-hq:OIznQNWGQIGXE4DbypgODTcP
      on_success: always
      on_failure: never
      if: type = pull_request
      template:
        - 'Pull Request <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of *%{repository_name}@%{branch}* by _%{author}_ *%{result}*! :white_check_mark:'
        - 'Time: *%{duration}*'
        - 'Commit: _%{commit_subject}_'
    - rooms:
        - glpg-hq:OIznQNWGQIGXE4DbypgODTcP
      on_success: never
      on_failure: always
      if: type = push
      template:
        - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of *%{repository_name}@%{branch}* by _%{author}_ *%{result}*! :rotating_light:'
        - 'Time: *%{duration}*'
        - 'Commit: _%{commit_subject}_'
    - rooms:
        - glpg-hq:OIznQNWGQIGXE4DbypgODTcP
      on_success: never
      on_failure: always
      if: type = pull_request
      template:
        - 'Pull Request <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of *%{repository_name}@%{branch}* by _%{author}_ *%{result}*! :rotating_light:'
        - 'Time: *%{duration}*'
        - 'Commit: _%{commit_subject}_'
